---
- name: copy kubernetes cert config
  copy:
    src: kubernetes-csr.json
    dest: /tmp/certs/kubernetes-csr.json

- name: copy ca key
  copy:
    src: csr/ca/ca-key.pem
    dest: /etc/ssl/certs/
  become: true

- name: generate kubernetes cert
  command: >
    bash -c
    "$GOPATH/bin/cfssl gencert
    -ca=/etc/ssl/certs/ca.pem
    -ca-key=/etc/ssl/certs/ca-key.pem
    -config=/tmp/certs/ca-config.json
    -hostname=10.32.0.1,10.240.0.10,10.240.0.11,10.240.0.12,{{ public_ip }},127.0.0.1,kubernetes.default
    -profile=kubernetes
    /tmp/certs/kubernetes-csr.json | $GOPATH/bin/cfssljson -bare /etc/ssl/certs/kubernetes"
  become: true

- name: cleanup cert configs
  file:
    name: /tmp/certs/
    state: absent
  become: true