---
- name: restart kube-proxy
  service:
    name: kube-proxy
    state: restarted
  become: true

- name: restart kubelet
  service:
    name: kubelet
    state: restarted
  become: true

- name: restart containerd
  service:
    name: containerd
    state: restarted
  become: true

- name: restart cri-containerd
  service:
    name: cri-containerd
    state: restarted
  become: true