---
###############
#
# kubelet
#
###############

kubelet_allow_privileged: true

kubelet_anonymous_auth: false

kubelet_authorization_mode: Webhook

kubelet_cluster_dns: 10.32.0.10
kubelet_cluster_domain: cluster.local

kubelet_container_runtime: remote
kubelet_container_runtime_endpoint: unix:///var/run/cri-containerd.sock

kubelet_image_pull_progress_deadline: 2m

kubelet_network_plugin: cni

kubelet_register_node: true

kubelet_runtime_request_timeout: 15m

kubelet_restart_sec: 5



###############
#
# kube-proxy
#
###############
kube_proxy_proxy_mode: iptables

kube_proxy_restart_sec: 5